// packages/adapter-react/src/lib/MisMerge3.tsx
import '@mismerge/core/web';
import type { EditorColors, Highlighter, LineDiffAlgorithm } from '@mismerge/core';
import { useEffect, useRef } from 'react';

export function MisMerge3({
	lhs,
	ctr,
	rhs,
	onLhsChange,
	onCtrChange,
	onRhsChange,
	colors,
	lhsEditable,
	ctrEditable,
	rhsEditable,
	lineDiffAlgorithm,
	className,
	disableMerging,
	wrapLines,
	disableFooter,
	disableWordsCounter,
	disableBlocksCounter,
	highlight,
	ignoreWhitespace,
	ignoreCase,
	onConflictsResolvedChange
}: {
	lhs: string;
	ctr: string;
	rhs: string;
	onLhsChange?: (lhs: string) => void;
	onCtrChange?: (ctr: string) => void;
	onRhsChange?: (rhs: string) => void;
	colors?: EditorColors;
	lhsEditable?: boolean;
	ctrEditable?: boolean;
	rhsEditable?: boolean;
	lineDiffAlgorithm?: LineDiffAlgorithm;
	className?: string;
	disableMerging?: boolean;
	wrapLines?: boolean;
	disableFooter?: boolean;
	disableWordsCounter?: boolean;
	disableBlocksCounter?: boolean;
	highlight?: Highlighter;
	ignoreWhitespace?: boolean;
	ignoreCase?: boolean;
	onConflictsResolvedChange?: (conflictsResolved: boolean) => void;
}) {
	const ref = useRef<JSX.IntrinsicElements['mis-merge2']>(null);

	useEffect(() => {
		if (ref.current) {
			ref.current.highlight = highlight;
		}
	}, [highlight]);

	return (
		<mis-merge3
			ref={ref}
			lhs={lhs}
			ctr={ctr}
			rhs={rhs}
			onInput={() => {
				if (onLhsChange) {
					onLhsChange(ref.current.lhs);
				}

				if (onCtrChange) {
					onCtrChange(ref.current.ctr);
				}

				if (onRhsChange) {
					onRhsChange(ref.current.rhs);
				}

				if (onConflictsResolvedChange) {
					onConflictsResolvedChange(ref.current.conflictsResolved);
				}
			}}
			colors={JSON.stringify(colors)}
			lhsEditable={lhsEditable}
			ctrEditable={ctrEditable}
			rhsEditable={rhsEditable}
			lineDiffAlgorithm={lineDiffAlgorithm}
			class={className}
			disableMerging={disableMerging}
			wrapLines={wrapLines}
			disableFooter={disableFooter}
			disableWordsCounter={disableWordsCounter}
			disableBlocksCounter={disableBlocksCounter}
			highlight={highlight}
			ignoreWhitespace={ignoreWhitespace}
			ignoreCase={ignoreCase}
		/>
	);
}

// packages/adapter-vue/src/lib/MisMerge3.vue
<script setup lang="ts">
import '@mismerge/core/web';
import type { EditorColors, Highlighter, LineDiffAlgorithm } from '@mismerge/core';
import { ref } from 'vue';

const elem = ref<any>(null);

const props = defineProps<{
	lhs: string;
	ctr: string;
	rhs: string;
	onLhsChange?: (value: string) => void;
	onCtrChange?: (value: string) => void;
	onRhsChange?: (value: string) => void;
	colors?: EditorColors;
	lhsEditable?: boolean;
	ctrEditable?: boolean;
	rhsEditable?: boolean;
	lineDiffAlgorithm?: LineDiffAlgorithm;
	className?: string;
	disableMerging?: boolean;
	wrapLines?: boolean;
	disableFooter?: boolean;
	disableWordsCounter?: boolean;
	disableBlocksCounter?: boolean;
	highlight?: Highlighter;
	ignoreWhitespace?: boolean;
	ignoreCase?: boolean;
	onConflictsResolvedChange?: (conflictsResolved: boolean) => void;
}>();

function onInput() {
	if (!elem.value) {
		return;
	}

	if (props.onLhsChange) {
		props.onLhsChange(elem.value.lhs);
	}
	if (props.onCtrChange) {
		props.onCtrChange(elem.value.ctr);
	}
	if (props.onRhsChange) {
		props.onRhsChange(elem.value.rhs);
	}

	if (props.onConflictsResolvedChange) {
		props.onConflictsResolvedChange(elem.value.conflictsResolved);
	}
}
</script>

<template>
	<mis-merge3
		ref="elem"
		:lhs="props.lhs"
		:ctr="props.ctr"
		:rhs="props.rhs"
		@input="onInput"
		:colors="props.colors"
		:lhsEditable="props.lhsEditable"
		:ctrEditable="props.ctrEditable"
		:rhsEditable="props.rhsEditable"
		:lineDiffAlgorithm="props.lineDiffAlgorithm"
		:class="props.className"
		:disableMerging="props.disableMerging"
		:wrapLines="props.wrapLines"
		:disableFooter="props.disableFooter"
		:disableWordsCounter="props.disableWordsCounter"
		:disableBlocksCounter="props.disableBlocksCounter"
		:highlight="props.highlight"
		:ignoreWhitespace="props.ignoreWhitespace"
		:ignoreCase="props.ignoreCase"
	/>
</template>
